# frozen_string_literal: true

source 'http://rubygems.org'

gem 'activerecord'
gem 'json'
gem 'pry'
gem 'rack-test'
gem 'rspec'
gem 'sinatra'
gem 'sqlite3'
gem 'typhoeus'

# Audits the locked gems against the Ruby Advisory Database:
#   bundle exec bundle-audit check --update
gem 'bundler-audit', require: false, groups: %i[development test]
