# frozen_string_literal: true

require 'rubygems'
require 'active_record'
require 'yaml'
require 'logger'

desc 'Load the environment'
task :environment do
  env = ENV['SINATRA_ENV'] || 'development'
  databases = YAML.load_file('config/database.yml')
  ActiveRecord::Base.establish_connection(databases[env])
end

namespace :db do
  require_relative './db/migrate/001_create_users'

  desc 'Migrate the database'
  task(migrate: :environment) do
    ActiveRecord::Base.logger = Logger.new(STDOUT)
    ActiveRecord::Migration.verbose = true
    CreateUsers.up
  end
end
