# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord'
gem 'sinatra'

# Audits the locked gems against the Ruby Advisory Database:
#   bundle exec bundle-audit check --update
gem 'bundler-audit', require: false, groups: %i[development test]
